"""Generates src/components/ProductStory.astro, src/scripts/story.config.js and src/scripts/story.js.
Run from anywhere: python3 reference/gen_story.py
Scenes are built from the Figma frames "Start state" (6:67) and "End state" (6:56): every mock is an actor
with a start pose and an end pose in percent of a 16:9 stage that maps to the 1204-wide column (x 118..1322)."""
import json, os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SX, SW = 118, 1204          # stage x origin and width in Figma px
SH = SW * 9 / 16            # stage height in Figma px
def P(x=None, y=None, w=None, h=None, y0=0, **k):
    """Figma px -> stage %. y0 is the Figma y where this scene's stage starts."""
    d = {}
    if x is not None: d["x"] = round((x - SX) / SW * 100, 2)
    if y is not None: d["y"] = round((y - y0) / SH * 100, 2)
    if w is not None: d["w"] = round(w / SW * 100, 2)
    if h is not None: d["h"] = round(h / SH * 100, 2)
    d.update(k); return d

def img(src, alt, frame="photo"):
    return f'<figure class="mock {frame}"><img src="/assets/story/{src}" alt="{alt}" /></figure>'

# ---------------- Capture: analog inputs become Clad screens ----------------
Y1 = 330
capture = {
  "id": "capture", "name": "Capture", "title": "Record everything you need from the field in a single place",
  "html": (
    f'<div class="act skin" data-a="sketch">{img("capture-sketch.png","Handwritten field sketch on paper")}{img("capture-map.png","Clad field map with a redlined bore and its quantity form")}</div>'
    f'<div class="act skin" data-a="sheet">{img("capture-spreadsheet.png","Concrete volume and cost spreadsheet")}{img("capture-production.png","Clad production table with budgeted, progress to date and item quantities")}</div>'
    f'<div class="act" data-a="gmail"><div class="gmail">{img("capture-gmail.png","Gmail","icon")}<span class="badge">8,201</span></div></div>'
  ),
  "actors": [
    {"id": "sketch", "kf": [P(367, 344, 366, 244, Y1, at=.0, r=-2.5), P(367, 344, 366, 244, Y1, at=.18, r=-2.5), P(136, 417, 493.5, 329, Y1, at=.62, r=0)], "skin": [.36, .56]},
    {"id": "sheet",  "kf": [P(623, 523, 483, 193, Y1, at=.0, r=5), P(623, 523, 483, 193, Y1, at=.22, r=5), P(677, 417, 631, 315, Y1, at=.66, r=0)], "skin": [.42, .6]},
    {"id": "gmail",  "kf": [P(783, 344, 87, 87, Y1, at=.0, o=1, s=1), P(783, 344, 87, 87, Y1, at=.2, o=1, s=1), P(783, 300, 87, 87, Y1, at=.4, o=0, s=.85)]},
  ],
}

# ---------------- Manage: the board makes room for insights ----------------
Y2 = 1158
manage = {
  "id": "manage", "name": "Manage", "title": "Connect the dots on all the projects you manage",
  "html": (
    f'<div class="act" data-a="kanban">{img("manage-kanban.png","Clad project board: Not Started, Permitting, Make Ready, Construction","app")}</div>'
    f'<div class="act" data-a="chart">{img("manage-chart.png","Weekly production report line chart across five projects")}</div>'
  ),
  "actors": [
    {"id": "kanban", "kf": [P(300, 1170, 841, 386, Y2, at=.0), P(300, 1170, 841, 386, Y2, at=.25), P(192, 1170, 408, 187, Y2, at=.62)]},
    {"id": "chart",  "kf": [P(667, 1220, 643, 429, Y2, at=.0, o=0), P(667, 1220, 643, 429, Y2, at=.42, o=0), P(667, 1167, 643, 429, Y2, at=.72, o=1)]},
  ],
}

# ---------------- Bill: (end state not designed yet; the invoice comes forward) ----------------
Y3 = 1968
bill = {
  "id": "bill", "name": "Bill", "title": "Generate accurate invoices and eliminate over- or under-billing",
  "html": (
    f'<div class="act" data-a="items">{img("bill-items.png","Invoice line items being entered by hand")}</div>'
    f'<div class="act" data-a="invoice">{img("bill-invoice.png","Finished invoice, $10,419.60 due October 1, 2026")}</div>'
  ),
  "actors": [
    {"id": "items",   "kf": [P(144, 2067, 539, 325, Y3, at=.0, o=1), P(144, 2067, 539, 325, Y3, at=.3, o=1), P(120, 2110, 539, 325, Y3, at=.7, o=.55)]},
    {"id": "invoice", "kf": [P(756, 1968, 512, 472, Y3, at=.0, s=1), P(756, 1968, 512, 472, Y3, at=.3, s=1), P(716, 1972, 512, 472, Y3, at=.7, s=1.05)]},
  ],
}

SCENES = [capture, manage, bill]

scenes_html = ""
for sc in SCENES:
    scenes_html += f'''
  <section class="scene" id="story-{sc["id"]}" data-scene="{sc["id"]}">
    <div class="pin">
      <div class="head">
        <span class="label">{sc["name"]}</span>
        <h3>{sc["title"]}</h3>
      </div>
      <div class="stage">{sc["html"]}</div>
    </div>
  </section>'''

astro = f'''---
/* Product story: three scroll-scrubbed scenes (Capture, Manage, Bill) built from the Figma
   "Start state" / "End state" frames. GENERATED by reference/gen_story.py; edit the generator. */
---
<div class="story container-wide" id="story" aria-label="How Clad works">{scenes_html}
</div>

<script src="../scripts/story.js"></script>

<style is:global>
  .story {{ margin-top: 148px; margin-bottom: 86px; }}
  .story .scene {{ position: relative; height: 300vh; }}
  .story .pin {{
    position: sticky; top: calc(72px + 20px); height: calc(100vh - 72px - 40px);
    display: flex; flex-direction: column; gap: 28px;
  }}
  .story .head {{ display: flex; flex-direction: column; gap: 14px; }}
  .story .head .label {{ font-family: var(--font-mono); font-size: 15px; font-weight: 700; letter-spacing: .75px; text-transform: uppercase; color: var(--color-cobalt); line-height: 1.2; }}
  .story .head h3 {{ font-size: var(--text-h2); line-height: 1.2; letter-spacing: -1.5px; font-weight: 600; max-width: 650px; }}
  .story .stage {{
    position: relative; flex: 1; min-height: 0; overflow: visible;
    aspect-ratio: 16 / 9; width: auto; max-width: 100%; align-self: center;
  }}
  .story .act {{ position: absolute; transform-origin: center; }}
  .story .skin .mock {{ position: absolute; inset: 0; }}
  .story .skin .mock + .mock {{ opacity: 0; }}
  .story .mock {{ margin: 0; width: 100%; height: 100%; overflow: hidden; background: var(--color-paper); }}
  .story .mock img {{ width: 100%; height: 100%; object-fit: cover; display: block; }}
  /* "Mocks Drop Shadow" from Figma, two frame styles */
  .story .mock.photo {{ border: 8px solid #fff; border-radius: 4px; box-shadow: 0 0 0 1px rgb(0 0 0 / .2), 0 0 2px rgb(0 0 0 / .08), 0 2px 6px rgb(0 0 0 / .1); }}
  .story .mock.app {{ border-radius: 10px; box-shadow: 0 0 4px rgb(0 0 0 / .25), 0 2px 6px rgb(0 0 0 / .1), 0 0 2px rgb(0 0 0 / .08); }}
  .story .mock.icon {{ border: 1.25px solid #eee; border-radius: 27.5%; box-shadow: 0 0 5px rgb(0 0 0 / .25), 0 2.5px 7.5px rgb(0 0 0 / .1), 0 0 2.5px rgb(0 0 0 / .08); }}
  .story .mock.icon img {{ object-fit: contain; padding: 6%; }}
  .story .gmail {{ position: relative; width: 100%; height: 100%; }}
  .story .gmail .badge {{ position: absolute; right: -10%; top: -14%; background: #ea3939; color: #fff; border-radius: 999px; padding: .35em .9em; font-size: clamp(9px, 1.05cqw, 12.5px); line-height: 1.2; }}
  .story .stage {{ container-type: size; }}
  @media (max-width: 900px) {{
    .story {{ margin-top: 72px; margin-bottom: 56px; }}
    .story .scene {{ height: 240vh; }}
    .story .pin {{ top: calc(64px + 12px); height: calc(100vh - 64px - 24px); gap: 16px; justify-content: flex-start; }}
    .story .head h3 {{ font-size: 26px; letter-spacing: -.5px; }}
    .story .stage {{ flex: none; width: 100%; height: auto; }}
    .story .mock.photo {{ border-width: 4px; }}
  }}
</style>
'''
open(f"{ROOT}/src/components/ProductStory.astro", "w").write(astro.replace("{{", "{").replace("}}", "}"))

config = "// Generated by reference/gen_story.py from Figma frames 6:67 (start) and 6:56 (end). Poses are % of the stage; `at` is scroll progress 0..1.\n"
config += "export const SCENES = " + json.dumps([{"id": sc["id"], "actors": sc["actors"]} for sc in SCENES]) + ";\n"
open(f"{ROOT}/src/scripts/story.config.js", "w").write(config)

engine = '''import { SCENES } from "./story.config.js";

// Scroll-scrubbed keyframe engine. Each scene is a tall section with a sticky stage; progress p (0..1)
// is how far the section has scrolled, and every actor's pose is interpolated from its keyframes.
// An actor with a `skin` range crossfades its first child into its second across that range.
const reduce = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
const clamp = (v, a, b) => Math.max(a, Math.min(b, v));
const smooth = (p, a, b) => { const t = clamp((p - a) / (b - a), 0, 1); return t * t * (3 - 2 * t); };
const ease = (t) => (t < 0.5 ? 4 * t * t * t : 1 - Math.pow(-2 * t + 2, 3) / 2);
const UNITS = { x: "left", y: "top", w: "width", h: "height" };

function apply(el, pose) {
  for (const k in UNITS) if (pose[k] != null) el.style[UNITS[k]] = pose[k] + "%";
  if (pose.o != null) el.style.opacity = pose.o;
  if (pose.r != null || pose.s != null)
    el.style.transform = (pose.r != null ? `rotate(${pose.r}deg) ` : "") + (pose.s != null ? `scale(${pose.s})` : "");
}

function poseAt(kf, p) {
  if (p <= kf[0].at) return kf[0];
  if (p >= kf[kf.length - 1].at) return kf[kf.length - 1];
  for (let i = 0; i < kf.length - 1; i++) {
    const a = kf[i], b = kf[i + 1];
    if (p >= a.at && p <= b.at) {
      const t = ease((p - a.at) / (b.at - a.at)), out = {};
      for (const k in a) { if (k === "at") continue; out[k] = typeof a[k] === "number" && typeof b[k] === "number" ? a[k] + (b[k] - a[k]) * t : a[k]; }
      return out;
    }
  }
  return kf[kf.length - 1];
}

function mount(cfg) {
  const sec = document.getElementById(`story-${cfg.id}`);
  if (!sec) return;
  const stage = sec.querySelector(".stage");
  const actors = cfg.actors.map((a) => ({ ...a, el: stage.querySelector(`.act[data-a="${a.id}"]`) }));
  let ticking = false;

  function render(p) {
    for (const a of actors) {
      if (!a.el) continue;
      apply(a.el, poseAt(a.kf, p));
      if (a.skin) { const k = smooth(p, a.skin[0], a.skin[1]); a.el.children[0].style.opacity = 1 - k; a.el.children[1].style.opacity = k; }
    }
  }
  function measure() {
    ticking = false;
    const r = sec.getBoundingClientRect(), total = sec.offsetHeight - window.innerHeight;
    const p = clamp(-r.top / total, 0, 1);
    render(reduce ? (p < 0.5 ? 0 : 1) : p);
  }
  window.addEventListener("scroll", () => { if (!ticking) { ticking = true; requestAnimationFrame(measure); } }, { passive: true });
  window.addEventListener("resize", measure);
  measure();
}

SCENES.forEach(mount);
'''
open(f"{ROOT}/src/scripts/story.js", "w").write(engine)
print("generated")
